### ISSUE TITLE
Add a new modifier for "Auto-margin" grid

### ISSUE THREAD

**Issue by georgiecel** [campaignmonitor/shell#117]
```scss
.l-grid__item--auto-margin-left {
    margin-right: auto;
}
```
