### ISSUE TITLE
Add a new "Spacing none" helper

### ISSUE THREAD

**Issue by chris-pearce** [campaignmonitor/shell#62]
I found this is needed, something like:

``` scss
.h-spacing-none {
    margin-bottom: 0 !important;
}
```

Can be added to the existing **Spacing** section in `_helpers.scss`.
