### ISSUE TITLE
12 col grid item CSS missing from Grid

### ISSUE THREAD

**Issue by chris-pearce** [campaignmonitor/shell#64]
It got added as a setting in `_settings.scss` but not in `_grid.scss` 😢.

Should come after:

``` scss
// 11 col
.l-grid__item--11-col {
    width: $shell-grid-11-col-width;
}

// Apply at breakpoints
@if $shell-grid-apply-11-col-width-at-breakpoints {
    @include apply-at-breakpoints(".l-grid__item--11-col", $shell-grid-define-11-col-width-breakpoints) {
        width: $shell-grid-11-col-width;
    }
}
```
