### ISSUE TITLE
Add a new Helper to remove responsive images

### ISSUE THREAD

**Issue by chris-pearce** [campaignmonitor/shell#71]
This is currently in `_base.scss` -> Images:

``` scss
/**
 * Third-party widgets—like Google Maps—cannot have their images be responsive
 * as this breaks any images used within them therefore we remove that by
 * applying the two possible Google Map container selectors plus a generic
 * container selector to be used for other third-party widgets.
 *
 * N.B. it is okay to use `!important` here as we're doing it pre-emptively
 * i.e. you know you will always want the rule it's applied to to take
 * precedence.
 */

/* stylelint-disable */

.remove-responsive-images img,
#map_canvas img,
.map_canvas img {
    max-width: none !important;
}

/* stylelint-enable */
```

It should be in `_helpers.scss`.
