### ISSUE TITLE
Apply Campaign Monitor CSS conventions via Stylelint, and update Stylelint

### ISSUE THREAD

**Issue by chris-pearce** [campaignmonitor/shell#72]
When this happens review all stylelint disable/enable comments, e.g.

``` scss
@mixin hidpi-bg-img($img-url, $img-width: auto, $img-height: auto) {
    /* stylelint-disable */
    @media (min-resolution: $shell-g-hidpi-dppx),
           (min-resolution: $shell-g-hidpi-dpi) {
    /* stylelint-enable */
        background-image: url('#{$img-url}');
        background-size: $img-width $img-height;
    }
}
```

Make sure to update the config file and remove `stylelint_config.js`.
