### ISSUE TITLE
Remove spinner from `number` input type

### ISSUE THREAD

**Issue by chris-pearce** [campaignmonitor/shell#82]
This may be the CSS to use but make sure it's properly checked:

``` scss
input[type='number'] {
    appearance: textfield;
}

input[type='number']::-webkit-inner-spin-button,
input[type='number']::-webkit-outer-spin-button,
input[type='number']:hover::-webkit-inner-spin-button,
input[type='number']:hover::-webkit-outer-spin-button {
    appearance: none;
}
```
