### ISSUE TITLE
Add `:disabled` rule to button css in Normalise/Reset

### ISSUE THREAD

**Issue by chris-pearce** [campaignmonitor/shell#96]
In `_normalise-reset.scss` there's this declaration:

```scss
button,
html [type='button'], // [1]
[type='reset'],
[type='submit'] {
    /* stylelint-disable-next-line property-no-vendor-prefix */
    -webkit-appearance: button; // [3]
    cursor: pointer; // [2]
}
```

If any of the above elements are disabled via the `disabled` attr then the `cursor: not-allowed;` rule from this declaration won't work:

```scss
:disabled {
    cursor: not-allowed;
    pointer-events: none;
}
```

As it is overridden by the `cursor: pointer;` rule. 

Either review these rules or add this:

```scss
&:disabled {
    cursor: not-allowed;
}
```

So:

```scss
button,
html [type='button'], // [1]
[type='reset'],
[type='submit'] {
    /* stylelint-disable-next-line property-no-vendor-prefix */
    -webkit-appearance: button; // [3]
    cursor: pointer; // [2]

    &:disabled {
         cursor: not-allowed;
    }
}
```

**Comment by chris-pearce** [comment]
I think it's best to just ditch:

```scss
:disabled {
    cursor: not-allowed;
    pointer-events: none;
}
```

As in most cases it won't apply due to specificity. 

@DaveOrDead thoughts?

**Comment by chris-pearce** [comment]
I've added a new section to the CMDS settings as part of a CMDS PR:

```scss
/* 3. Disabled
   ========================================================================= */

/**
 * When an element is in a disabled state, typically applied via the `disabled`
 * attribute.
 */

$g-disabled-opacity: 0.6;
```

We could add another setting for `cursor: not-allowed;`? Or write it as a `@mixin`, e.g.:

```scss
@mixin disabled {
    opacity: 0.6;
    cursor: not-allowed;
}
```
