### ISSUE TITLE
Create a "disabled" Mixin

### ISSUE THREAD

**Issue by chris-pearce** [campaignmonitor/shell#97]
There are styles common to when an element is in a disabled state so we should handle this via a mixin to keep things DRY, which can reside in the [Shared styles](https://github.com/campaignmonitor/shell/blob/master/src/_mixins-functions.scss#L958) section of `_mixins-functions.scss`.

Something like this:

```scss
@mixin disabled {
    cursor: not-allowed;
    opacity: $shell-g-opacity-disabled;
    pointer-events: none;
}
```

Applied like this:

```scss
&:disabled {
    @include disabled;
    […]
}
```

See: #96.

@DaveOrDead @davidberner FYI.
